services:
  devops:
    build: .
    image: devops:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - devopsNet

networks:
  devopsNet:
    external: true

#> docker compose up --build -d